In [506]:
import torch

x = torch.arange(4)
x, x[3], len(x)

(tensor([0, 1, 2, 3]), tensor(3), 4)

In [507]:
A = torch.arange(20).reshape(5, 4)
A, A.T #转置

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]))

In [508]:
#对称矩阵 A = A.T
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [509]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [510]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [511]:
A = torch.arange(20).reshape(4, 5)
B = A.clone()
A, A + B

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([[ 0,  2,  4,  6,  8],
         [10, 12, 14, 16, 18],
         [20, 22, 24, 26, 28],
         [30, 32, 34, 36, 38]]))

In [512]:
#哈达玛积, 同位置相乘
A * B

tensor([[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81],
        [100, 121, 144, 169, 196],
        [225, 256, 289, 324, 361]])

In [513]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [514]:
#计算元素的和
x = torch.arange(4, dtype=torch.float32).reshape(2, 2)
x, x.sum()

(tensor([[0., 1.],
         [2., 3.]]),
 tensor(6.))

In [515]:
#sum可以表示任意张量的元素的和
A.shape, A.sum()

(torch.Size([4, 5]), tensor(190))

In [516]:
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [517]:
#可以指定求和汇总张量的轴，即沿某一方向求和
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([30, 34, 38, 42, 46]), torch.Size([5]))

In [518]:
A_sum_axis0 = A.sum(axis=1)
A_sum_axis0, A_sum_axis0.shape

(tensor([10, 35, 60, 85]), torch.Size([4]))

In [519]:
A.sum(axis=[0, 1]) #相当于A.sum()

tensor(190)

In [520]:
x.mean(), x.sum() / x.numel()

(tensor(1.5000), tensor(1.5000))

In [521]:
x

tensor([[0., 1.],
        [2., 3.]])

In [522]:
x.mean(axis=1), x.sum(axis=1) / x.shape[1]

(tensor([0.5000, 2.5000]), tensor([0.5000, 2.5000]))

In [523]:
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [524]:
# 使用keepdim压缩求和时保证维度不变
sum_A = A.sum(axis=1, keepdim=True)
sum_A

tensor([[10],
        [35],
        [60],
        [85]])

In [525]:
# 通过广播将A除以sum_A
A / sum_A

tensor([[0.0000, 0.1000, 0.2000, 0.3000, 0.4000],
        [0.1429, 0.1714, 0.2000, 0.2286, 0.2571],
        [0.1667, 0.1833, 0.2000, 0.2167, 0.2333],
        [0.1765, 0.1882, 0.2000, 0.2118, 0.2235]])

In [526]:
A.cumsum(axis=0) #沿第一个维度（行）求累计和，即前缀和

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  7,  9, 11, 13],
        [15, 18, 21, 24, 27],
        [30, 34, 38, 42, 46]])

In [527]:
x = torch.arange(4).float()
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y) #点积

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [528]:
torch.sum(x * y)

tensor(6.)

In [529]:
#矩阵相乘
A = torch.ones(5, 4)
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [530]:
# L2范数
u = torch.tensor([3.0, -4.0])
torch.norm(u) #Norm范数

tensor(5.)

In [531]:
# L1范数,表示向量各元素的绝对值之和
torch.abs(u).sum()

tensor(7.)

In [ ]:
# F范数
torch.norm(torch.ones(4, 9))

tensor(6.)