In [6]:
#导入第三方库
import torch

In [7]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
x.shape

torch.Size([12])

In [9]:
x.numel()

12

In [10]:
y = x.reshape(3, 4)
y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
z = x.reshape(-1, 4)
z

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
m = torch.ones(2, 3)
m

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
m[:, 1]

tensor([1., 1.])